name: CI

on:
  create:
     tags:
       - '*'
  workflow_dispatch:  

  
jobs:
  build:
    runs-on: macos-11

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Make build file for various oses
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          env GOOS=linux go build -ldflags="-s -w -X main.GitCommit=$GIT_COMMIT -X 'main.GitRelease=${GITHUB_REF##*/}' -X main.GitBranch=${branch//[[:space:]]/}" -o rc/lrc_linux .
          env GOOS=darwin go build -ldflags="-s -w -X main.GitCommit=$GIT_COMMIT -X 'main.GitRelease=${GITHUB_REF##*/}' -X main.GitBranch=${branch//[[:space:]]/}" -o rc/lrc_macos .
          env GOOS=windows go build -ldflags="-s -w -X main.GitCommit=$GIT_COMMIT -X 'main.GitRelease=${GITHUB_REF##*/}' -X main.GitBranch=${branch//[[:space:]]/}" -o rc/lrc_windows.exe .